# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
field_selection:
  transaction_fields:
    - hash
    - from

networks:
  - id: 10143
    start_block: 0
    contracts:
      - name: AmertisRouter
        address:
          - 0xD158Cb79C63F4852485E37F05D20da3093d143Ed
        handler: src/EventHandlers.ts
        events:
          - event: AmertisSwap(address indexed _tokenIn, address indexed _tokenOut, uint256 _amountIn, uint256 _amountOut)
unordered_multichain_mode: true
