# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
field_selection:
  transaction_fields:
    - hash
    - from

networks:
  - id: 10143
    start_block: 31487106
    contracts:
      - name: AmertisRouter
        address:
          - 0x69ae41041D61dEF300337c205250d0b9FfDBd3af
        handler: src/EventHandlers.ts
        events:
          - event: AmertisSwap(address indexed _tokenIn, address indexed _tokenOut, uint256 _amountIn, uint256 _amountOut, uint256 tokenValueUSD)
unordered_multichain_mode: true
